### ISSUE TITLE
Models can no longer be pickled

### ISSUE THREAD

**Issue by alexhayes** [schematics/schematics#510]
It appears that somewhere between version `2.0.0a1` and `2.0.1` models can no longer be pickled.

```python
import pickle
from schematics.models import Model
from schematics.types import IntType

class Foo(Model):
    bar = IntType()

f = Foo(dict(bar=1))

pickle.dumps(f)
```

Results in: `TypeError: can't pickle mappingproxy objects`

Note that I attempted to do a `git bisect start HEAD a8249f1 --` on master but there are many commits that are essentially broken thus bisect doesn't appear possible. Even if I modify the above script to return `125` if we can't determine the exit code (ie.. for issues like `cannot import name 'ComputedType'` and `No module named 'schematics.inspection'`) essentially git bisect gets to a point where there are only skipped commits left to test (ie.. dead end).

With a bit more digging I could ascertain that it was definitely broken by 65f3d95 and was good in b90990a so somewhere between those two it was broken.

This is perhaps related to #474.

**Comment by lkraider** [comment]
Thanks, I'll open a review for the pickling issues. It requires tests to make it a reliable feature.

**Comment by alexhayes** [comment]
@lkraider I can open a PR with tests if you like.

**Comment by lkraider** [comment]
All help is welcome! :)

**Comment by alexhayes** [comment]
Just to be sure `MappingProxyType` is not supposed to support pickle I've raised http://bugs.python.org/msg300284

**Comment by rooterkyberian** [comment]
For me this have caused problems during with deepcopying, so my workaround using [schematics 2.0.1](https://github.com/schematics/schematics/releases/tag/v2.0.1) is```py
def __deepcopy__(self, memo):
    copied = ModelDict(
        *map(lambda o: copy.deepcopy(o, memo),
        [self._unsafe, self._converted, self._ModelDict__valid]),
    )
    return copied

ModelDict.__deepcopy__ = __deepcopy__
```

it would be nice to get rid of this ugliness ASAP

**Comment by froxCZ** [comment]
I fixed it by implementing own Schematics base class and overriding pickle methods.
```
class PickableModel(schematics.Model):
    def __getstate__(self):
        # For pickle and depickle
        return self.to_native()

    def __setstate__(self, kwargs: Dict[str, any]):
        self.__init__(kwargs)
```

**Comment by ses4j** [comment]
Problem persists into `2.1.0`

**Comment by teck968** [comment]
May I request an update on the direction for this issue? 
I see that a fix has been committed approximately 2 years back, but hasn't been merged yet.

**Comment by fulcrumlabsio** [comment]
Would be great to have this aforementioned fix merged in!
