### ISSUE TITLE
Broken import in models.py

### ISSUE THREAD

**Issue by csojinb-picwell** [schematics/schematics#279]
Since the update to 1.0-1, I'm getting the following error that seems to be internal to the library:
```    
from schematics.types.compound import ListType
../../../virtualenv/python2.7.9/lib/python2.7/site-packages/schematics/types/compound.py:9: in <module>
    from ..models import Model
../../../virtualenv/python2.7.9/lib/python2.7/site-packages/schematics/models.py:435: in <module>
    from .types.compound import ModelType
E   ImportError: cannot import name ModelType
```
Looks like a circular import issue?

**Comment by kracekumar** [comment]
It is fixed in `1.0.2`. 

```
In [2]: schematics.version_info
Out[2]: ('1', '0', '2')

In [3]: from schematics.types.compound import ListType

```

Thanks for reporting.
